version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_ipn
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: IPN
      MYSQL_USER: kolo
      MYSQL_PASSWORD: SedAdmin.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./html/php-attendance/db:/docker-entrypoint-initdb.d
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_ipn
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./html/php-attendance:/usr/share/nginx/html
    networks:
      - webnet
    depends_on:
      - db

  php-app:
    build: ./php-app
    container_name: php-app
    depends_on:
      - db
    networks:
      - webnet
    ports:
      - "8000:80"
    restart: always

volumes:
  mysql_data:

networks:
  webnet:
    driver: bridge
